### ISSUE TITLE
Проблемы лицензирования

### ISSUE THREAD

**Issue by HIlight3R** [Frogdream/Launcher#1]
На данный момент в лаунчере присутствуют следующие проблемы, касающиеся лицензирования:

1. Нигде и никак, кроме файла EULA в репозитории не указано каким образом лицензируется данное ПО.
2. Пользователь обязан согласиться с лицензией для использования программы, факт принятия лицензии при запуске программы здесь недопустим.
3. В релизной версии для macOS в файле LICENSE в корне архива указана лицензия Apache License 2.0, указывающая на свободу использования, распространения и модификацию данного ПО, а также его исходного кода. Ни один из этих пунктов не может быть достигнут в полной мере.

**Comment by cubelius** [comment]
Поставили лицензию MIT. Вопрос о лицензировании был заморожен из-за проблемы выбора лицензии. Пользователя потом будем осведомлять о принятии лицензии.

И как же комично выглядит тот факт, что после того, что ты вытворил с Notion, ты помогаешь нам решать проблемы лаунчера. Забавно.

**Comment by HIlight3R** [comment]
Хм, ну начнем с того, что о том, что что-то натворил с Notion AxoRom я узнал не раньше чем через часов 8 после написания данного issue. Во-вторых, я лишь посмотрел что он сделал. В-третьих, после этого случая, лично мне все равно на то, что происходит с сервером на данный момент. Сервер медленно загибается по причине того, что администрация медленно, но верно теряет доверие игроков. Случай с nerulex'ом так вообще цирковой. Грифера, демагога и разжигателя национальных конфликтов привести к посту администрации сервера. Что-ж, рыба гниет с головы. К слову, скажу, что многие игроки знают об одной очень интересной серверной уязвимости, с которой игра на проекте становится абсолютно бессмысленной. Но это так, лирика. А то, что я услышал в оправдание своего бана, так это вообще смех, особенно дискредитация сервера. И в "Тишину" я попал только потому, что хотел пообщаться с Clyde'ом. Но до тебя вряд-ли что-то дойдет, да мне и особо не нужно. Я высказался, ответных комментариев можно не присылать, обойдусь ;)
