### ISSUE TITLE
Кнопка добавления друга ведет на несуществующую страницу

### ISSUE THREAD

**Issue by HIlight3R** [Frogdream/Launcher#2]
![image](https://github.com/Frogdream/Launcher/assets/66161627/33005241-2fd2-48b1-8d6f-8f7789fa3598)
Кнопка добавления друга ведет на несуществующую страницу https://frogdream.xyz/friend c ошибкой 404

**Comment by cubelius** [comment]
Знаю, потом добавим функционал
